services:
    tracking.laravel_gp_api:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # - '5050:80'
            - '${API_PORT:-80}:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - tracking
        depends_on:
            - tracking.mysql
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 600M
    tracking.mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            TZ: "America/Guayaquil"
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            #- './docker/mysql/my.cnf:/etc/my.cnf'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - tracking
        deploy:
            resources:
                limits:
                    cpus: '0.6'
                    memory: 1000M
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    tracking:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
